language: python
sudo: false
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- pytest --cov aws_lambda -v tests
after_success:
- coveralls
- echo 'Success!'
