language: python
sudo: false
python:
- '3.6'
install:
- pip install --upgrade pip==19.0.3
- pip install poetry
- poetry install
- pip install coveralls
script:
- pytest --cov aws_lambda -v tests
after_success:
- coveralls
- echo 'Success!'
